# Dockerfile for MSSQL
FROM mcr.microsoft.com/mssql/server:2017-latest
WORKDIR /home/mssql_scripts
COPY ./mssql_scripts/import_table.sh /home/mssql_scripts/
ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=P@ssw0rd
EXPOSE 1433
CMD /bin/bash /home/mssql_scripts/entrypoint.sh
